import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-center justify-center w-full bg-slate-50 dark:bg-slate-900 text-slate-950 dark:text-slate-50 text-[16px]`}
      >
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <div className="w-full mb-20"> {children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
