import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviders } from "@/src/theme/ThemeProviders";
import { AppProvider } from "@/src/contexts/AppContext";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Vault ICO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className="antialiased flex items-center justify-center w-full bg-slate-50 dark:bg-slate-900 text-slate-950 dark:text-slate-50 text-[16px]"
      >
        <Providers>
          <ThemeProviders>
            <AppProvider>
              <div className="max-w-[100vw] w-[100vW] mb-20"> {children}</div>
            </AppProvider>
          </ThemeProviders>
        </Providers>
      </body>
    </html>
  );
}
